
GIMPTOOL=/usr/i686-w64-mingw32/sys-root/mingw/bin/gimptool-2.0.exe

CC=i686-w64-mingw32-gcc
CFLAGS=-pipe -g -O2 -Wall -march=i686 -msse $(shell i686-w64-mingw32-pkg-config --cflags gtk+-2.0 gimp-2.0)
LDFLAGS=-mwindows

EXT=.exe

TARGET=dds$(EXT)

LIBS=$(shell i686-w64-mingw32-pkg-config --libs gtk+-2.0 gimp-2.0 gimpui-2.0) -lm
